
services:
  postges:
    image: postgres
    container_name: postgres-checker
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-checker
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  app:
    build: .
    container_name: bullmq-app
    restart: on-failure
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
    command: npm run dev

volumes:
  postgres_data:
  redis_data: